name: eiskaltdcpp
version: git
summary: file sharing program using Direct Connect protocols
description: |
  EiskaltDC++ is a cross-platform program that uses the Direct Connect and
  Advanced Direct Connect protocols. It is compatible with DC++, AirDC++,
  FlylinkDC++ and other DC clients. EiskaltDC++ also interoperates with all
  common DC hub software.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: armhf
    run-on: armhf
  - build-on: riscv64
    run-on: riscv64

base: core20

version-script: |
  set -x
  cd $SNAPCRAFT_PRIME/../parts/eiskalt/src
  vers=`git describe --tags`
  echo ${vers#"v"}

apps:
  eiskaltdcpp-env:
    command: env
    environment:
      HOME: "$SNAP_USER_COMMON"
  eiskaltdcpp:
    command: ./bin/desktop-launch $SNAP/usr/bin/eiskaltdcpp
    desktop: usr/share/applications/eiskaltdcpp-qt.desktop
    environment:
      DISABLE_WAYLAND: 1
      WAYLAND_DISPLAY: no-display
      QTCOMPOSE: $SNAP/usr/share/X11/locale
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - network-bind
      - network-manager
      - removable-media
      - pulseaudio
      - unity7

parts:
  eiskalt:
    after: [desktop-qt5]
    #source: .
    source: https://github.com/eiskaltdcpp/eiskaltdcpp.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DFORCE_XDG=OFF # use $HOME for configs, which we map to $SNAP_USER_COMMON
      - -DLINK=STATIC
      - -DUSE_XATTR=ON
      - -DWITH_LUASCRIPTS=ON
    build-packages:
      - gettext
      - libattr1-dev
      - libaspell-dev
      - libbz2-dev
      - libidn2-dev
      - liblua5.1-0-dev
      - libminiupnpc-dev
      - libpcre2-dev
      - libssl-dev
      - qtbase5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - zlib1g-dev
    stage-packages:
      - libaspell15
      - liblua5.1-0
      - libpcre2-16-0
      - libpulse0
      - libqt5concurrent5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5xml5
      - miniupnpc
      - qttranslations5-l10n
    override-prime: |
        snapcraftctl prime
        sed -i "s|^Icon=.*|Icon=\${SNAP}/usr/share/icons/hicolor/128x128/apps/eiskaltdcpp.png|g" usr/share/applications/eiskaltdcpp-qt.desktop
    organize:
      usr/bin/eiskaltdcpp-qt: usr/bin/eiskaltdcpp
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - dpkg-dev
      - qtbase5-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - libxkbcommon0
      - libgdk-pixbuf2.0-0
      - light-themes
      - libqt5gui5
      - libqt5multimedia5
      - libqt5svg5 # for loading icon themes which are svg
      - libqt5widgets5
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
